// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Calculator struct {
	FirtNumber           int32    `protobuf:"varint,1,opt,name=firt_number,json=firtNumber,proto3" json:"firt_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculator) Reset()         { *m = Calculator{} }
func (m *Calculator) String() string { return proto.CompactTextString(m) }
func (*Calculator) ProtoMessage()    {}
func (*Calculator) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{0}
}

func (m *Calculator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculator.Unmarshal(m, b)
}
func (m *Calculator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculator.Marshal(b, m, deterministic)
}
func (m *Calculator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculator.Merge(m, src)
}
func (m *Calculator) XXX_Size() int {
	return xxx_messageInfo_Calculator.Size(m)
}
func (m *Calculator) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculator.DiscardUnknown(m)
}

var xxx_messageInfo_Calculator proto.InternalMessageInfo

func (m *Calculator) GetFirtNumber() int32 {
	if m != nil {
		return m.FirtNumber
	}
	return 0
}

func (m *Calculator) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type CalculatorRequest struct {
	Calculate            *Calculator `protobuf:"bytes,1,opt,name=calculate,proto3" json:"calculate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CalculatorRequest) Reset()         { *m = CalculatorRequest{} }
func (m *CalculatorRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorRequest) ProtoMessage()    {}
func (*CalculatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{1}
}

func (m *CalculatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorRequest.Unmarshal(m, b)
}
func (m *CalculatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorRequest.Merge(m, src)
}
func (m *CalculatorRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorRequest.Size(m)
}
func (m *CalculatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorRequest proto.InternalMessageInfo

func (m *CalculatorRequest) GetCalculate() *Calculator {
	if m != nil {
		return m.Calculate
	}
	return nil
}

type CalculatorResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorResponse) Reset()         { *m = CalculatorResponse{} }
func (m *CalculatorResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatorResponse) ProtoMessage()    {}
func (*CalculatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{2}
}

func (m *CalculatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorResponse.Unmarshal(m, b)
}
func (m *CalculatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorResponse.Marshal(b, m, deterministic)
}
func (m *CalculatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorResponse.Merge(m, src)
}
func (m *CalculatorResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatorResponse.Size(m)
}
func (m *CalculatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorResponse proto.InternalMessageInfo

func (m *CalculatorResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeFactorDescomptition struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeFactorDescomptition) Reset()         { *m = PrimeFactorDescomptition{} }
func (m *PrimeFactorDescomptition) String() string { return proto.CompactTextString(m) }
func (*PrimeFactorDescomptition) ProtoMessage()    {}
func (*PrimeFactorDescomptition) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{3}
}

func (m *PrimeFactorDescomptition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeFactorDescomptition.Unmarshal(m, b)
}
func (m *PrimeFactorDescomptition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeFactorDescomptition.Marshal(b, m, deterministic)
}
func (m *PrimeFactorDescomptition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeFactorDescomptition.Merge(m, src)
}
func (m *PrimeFactorDescomptition) XXX_Size() int {
	return xxx_messageInfo_PrimeFactorDescomptition.Size(m)
}
func (m *PrimeFactorDescomptition) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeFactorDescomptition.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeFactorDescomptition proto.InternalMessageInfo

func (m *PrimeFactorDescomptition) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeFactorDescomptitionManyTimeRequest struct {
	Prime                *PrimeFactorDescomptition `protobuf:"bytes,1,opt,name=prime,proto3" json:"prime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PrimeFactorDescomptitionManyTimeRequest) Reset() {
	*m = PrimeFactorDescomptitionManyTimeRequest{}
}
func (m *PrimeFactorDescomptitionManyTimeRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeFactorDescomptitionManyTimeRequest) ProtoMessage()    {}
func (*PrimeFactorDescomptitionManyTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{4}
}

func (m *PrimeFactorDescomptitionManyTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeFactorDescomptitionManyTimeRequest.Unmarshal(m, b)
}
func (m *PrimeFactorDescomptitionManyTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeFactorDescomptitionManyTimeRequest.Marshal(b, m, deterministic)
}
func (m *PrimeFactorDescomptitionManyTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeFactorDescomptitionManyTimeRequest.Merge(m, src)
}
func (m *PrimeFactorDescomptitionManyTimeRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeFactorDescomptitionManyTimeRequest.Size(m)
}
func (m *PrimeFactorDescomptitionManyTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeFactorDescomptitionManyTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeFactorDescomptitionManyTimeRequest proto.InternalMessageInfo

func (m *PrimeFactorDescomptitionManyTimeRequest) GetPrime() *PrimeFactorDescomptition {
	if m != nil {
		return m.Prime
	}
	return nil
}

type PrimeFactorDescomptitionManyTimeResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeFactorDescomptitionManyTimeResponse) Reset() {
	*m = PrimeFactorDescomptitionManyTimeResponse{}
}
func (m *PrimeFactorDescomptitionManyTimeResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeFactorDescomptitionManyTimeResponse) ProtoMessage()    {}
func (*PrimeFactorDescomptitionManyTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{5}
}

func (m *PrimeFactorDescomptitionManyTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeFactorDescomptitionManyTimeResponse.Unmarshal(m, b)
}
func (m *PrimeFactorDescomptitionManyTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeFactorDescomptitionManyTimeResponse.Marshal(b, m, deterministic)
}
func (m *PrimeFactorDescomptitionManyTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeFactorDescomptitionManyTimeResponse.Merge(m, src)
}
func (m *PrimeFactorDescomptitionManyTimeResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeFactorDescomptitionManyTimeResponse.Size(m)
}
func (m *PrimeFactorDescomptitionManyTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeFactorDescomptitionManyTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeFactorDescomptitionManyTimeResponse proto.InternalMessageInfo

func (m *PrimeFactorDescomptitionManyTimeResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type LongCalculatorRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongCalculatorRequest) Reset()         { *m = LongCalculatorRequest{} }
func (m *LongCalculatorRequest) String() string { return proto.CompactTextString(m) }
func (*LongCalculatorRequest) ProtoMessage()    {}
func (*LongCalculatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{6}
}

func (m *LongCalculatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongCalculatorRequest.Unmarshal(m, b)
}
func (m *LongCalculatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongCalculatorRequest.Marshal(b, m, deterministic)
}
func (m *LongCalculatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongCalculatorRequest.Merge(m, src)
}
func (m *LongCalculatorRequest) XXX_Size() int {
	return xxx_messageInfo_LongCalculatorRequest.Size(m)
}
func (m *LongCalculatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongCalculatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongCalculatorRequest proto.InternalMessageInfo

func (m *LongCalculatorRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type LongCalculatorResponse struct {
	Number               float64  `protobuf:"fixed64,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongCalculatorResponse) Reset()         { *m = LongCalculatorResponse{} }
func (m *LongCalculatorResponse) String() string { return proto.CompactTextString(m) }
func (*LongCalculatorResponse) ProtoMessage()    {}
func (*LongCalculatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{7}
}

func (m *LongCalculatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongCalculatorResponse.Unmarshal(m, b)
}
func (m *LongCalculatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongCalculatorResponse.Marshal(b, m, deterministic)
}
func (m *LongCalculatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongCalculatorResponse.Merge(m, src)
}
func (m *LongCalculatorResponse) XXX_Size() int {
	return xxx_messageInfo_LongCalculatorResponse.Size(m)
}
func (m *LongCalculatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongCalculatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongCalculatorResponse proto.InternalMessageInfo

func (m *LongCalculatorResponse) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type MaximumEveryOneRequest struct {
	Calculate            *Calculator `protobuf:"bytes,1,opt,name=calculate,proto3" json:"calculate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MaximumEveryOneRequest) Reset()         { *m = MaximumEveryOneRequest{} }
func (m *MaximumEveryOneRequest) String() string { return proto.CompactTextString(m) }
func (*MaximumEveryOneRequest) ProtoMessage()    {}
func (*MaximumEveryOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{8}
}

func (m *MaximumEveryOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaximumEveryOneRequest.Unmarshal(m, b)
}
func (m *MaximumEveryOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaximumEveryOneRequest.Marshal(b, m, deterministic)
}
func (m *MaximumEveryOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaximumEveryOneRequest.Merge(m, src)
}
func (m *MaximumEveryOneRequest) XXX_Size() int {
	return xxx_messageInfo_MaximumEveryOneRequest.Size(m)
}
func (m *MaximumEveryOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaximumEveryOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaximumEveryOneRequest proto.InternalMessageInfo

func (m *MaximumEveryOneRequest) GetCalculate() *Calculator {
	if m != nil {
		return m.Calculate
	}
	return nil
}

type MaximumEveryOneResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaximumEveryOneResponse) Reset()         { *m = MaximumEveryOneResponse{} }
func (m *MaximumEveryOneResponse) String() string { return proto.CompactTextString(m) }
func (*MaximumEveryOneResponse) ProtoMessage()    {}
func (*MaximumEveryOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{9}
}

func (m *MaximumEveryOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaximumEveryOneResponse.Unmarshal(m, b)
}
func (m *MaximumEveryOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaximumEveryOneResponse.Marshal(b, m, deterministic)
}
func (m *MaximumEveryOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaximumEveryOneResponse.Merge(m, src)
}
func (m *MaximumEveryOneResponse) XXX_Size() int {
	return xxx_messageInfo_MaximumEveryOneResponse.Size(m)
}
func (m *MaximumEveryOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaximumEveryOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaximumEveryOneResponse proto.InternalMessageInfo

func (m *MaximumEveryOneResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SquareRootsRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootsRequest) Reset()         { *m = SquareRootsRequest{} }
func (m *SquareRootsRequest) String() string { return proto.CompactTextString(m) }
func (*SquareRootsRequest) ProtoMessage()    {}
func (*SquareRootsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{10}
}

func (m *SquareRootsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootsRequest.Unmarshal(m, b)
}
func (m *SquareRootsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootsRequest.Marshal(b, m, deterministic)
}
func (m *SquareRootsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootsRequest.Merge(m, src)
}
func (m *SquareRootsRequest) XXX_Size() int {
	return xxx_messageInfo_SquareRootsRequest.Size(m)
}
func (m *SquareRootsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootsRequest proto.InternalMessageInfo

func (m *SquareRootsRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SquareRootsResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootsResponse) Reset()         { *m = SquareRootsResponse{} }
func (m *SquareRootsResponse) String() string { return proto.CompactTextString(m) }
func (*SquareRootsResponse) ProtoMessage()    {}
func (*SquareRootsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{11}
}

func (m *SquareRootsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootsResponse.Unmarshal(m, b)
}
func (m *SquareRootsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootsResponse.Marshal(b, m, deterministic)
}
func (m *SquareRootsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootsResponse.Merge(m, src)
}
func (m *SquareRootsResponse) XXX_Size() int {
	return xxx_messageInfo_SquareRootsResponse.Size(m)
}
func (m *SquareRootsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootsResponse proto.InternalMessageInfo

func (m *SquareRootsResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Calculator)(nil), "calculator.Calculator")
	proto.RegisterType((*CalculatorRequest)(nil), "calculator.CalculatorRequest")
	proto.RegisterType((*CalculatorResponse)(nil), "calculator.CalculatorResponse")
	proto.RegisterType((*PrimeFactorDescomptition)(nil), "calculator.PrimeFactorDescomptition")
	proto.RegisterType((*PrimeFactorDescomptitionManyTimeRequest)(nil), "calculator.PrimeFactorDescomptitionManyTimeRequest")
	proto.RegisterType((*PrimeFactorDescomptitionManyTimeResponse)(nil), "calculator.PrimeFactorDescomptitionManyTimeResponse")
	proto.RegisterType((*LongCalculatorRequest)(nil), "calculator.LongCalculatorRequest")
	proto.RegisterType((*LongCalculatorResponse)(nil), "calculator.LongCalculatorResponse")
	proto.RegisterType((*MaximumEveryOneRequest)(nil), "calculator.MaximumEveryOneRequest")
	proto.RegisterType((*MaximumEveryOneResponse)(nil), "calculator.MaximumEveryOneResponse")
	proto.RegisterType((*SquareRootsRequest)(nil), "calculator.SquareRootsRequest")
	proto.RegisterType((*SquareRootsResponse)(nil), "calculator.SquareRootsResponse")
}

func init() {
	proto.RegisterFile("calculatorpb/calculator.proto", fileDescriptor_87e717c78a24322a)
}

var fileDescriptor_87e717c78a24322a = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0xcf, 0xd2, 0x40,
	0x10, 0x75, 0x35, 0xdf, 0x97, 0x38, 0x20, 0xc6, 0x35, 0x56, 0xd2, 0x04, 0xd1, 0xc5, 0x44, 0x0e,
	0x08, 0x08, 0x9c, 0x3c, 0x22, 0x9a, 0x98, 0x08, 0x92, 0xe2, 0x49, 0x0f, 0x5a, 0xea, 0x68, 0x9a,
	0xd0, 0x6e, 0xd9, 0xdd, 0x12, 0xf9, 0x13, 0xfc, 0xab, 0x35, 0xfd, 0x45, 0xb7, 0x40, 0xa9, 0xe6,
	0x3b, 0xce, 0xec, 0x7b, 0x6f, 0x66, 0x76, 0xde, 0x2e, 0xb4, 0x1c, 0x7b, 0xe3, 0x84, 0x1b, 0x5b,
	0x71, 0x11, 0xac, 0x07, 0x79, 0xd0, 0x0f, 0x04, 0x57, 0x9c, 0x42, 0x9e, 0x61, 0x16, 0xc0, 0x9b,
	0x43, 0x44, 0xdb, 0x50, 0xfb, 0xe1, 0x0a, 0xf5, 0xd5, 0x0f, 0xbd, 0x35, 0x8a, 0x26, 0x79, 0x4a,
	0xba, 0x57, 0x16, 0x44, 0xa9, 0x45, 0x9c, 0xa1, 0x1d, 0xb8, 0x27, 0xd1, 0xe1, 0xfe, 0xf7, 0x0c,
	0x72, 0x3b, 0x86, 0xd4, 0x93, 0x64, 0x02, 0x62, 0xef, 0xe1, 0x41, 0xae, 0x69, 0xe1, 0x36, 0x44,
	0xa9, 0xe8, 0x04, 0xee, 0x66, 0x65, 0x31, 0x16, 0xae, 0x8d, 0x8c, 0xbe, 0xd6, 0x9a, 0xc6, 0xc8,
	0x81, 0xac, 0x07, 0x54, 0x97, 0x92, 0x01, 0xf7, 0x25, 0x52, 0x03, 0xae, 0x05, 0xca, 0x70, 0xa3,
	0xd2, 0x0e, 0xd3, 0x88, 0x8d, 0xa0, 0xb9, 0x14, 0xae, 0x87, 0xef, 0x6c, 0x47, 0x71, 0x31, 0x43,
	0xe9, 0x70, 0x2f, 0x50, 0xae, 0x72, 0xb9, 0x1f, 0x71, 0x0a, 0x53, 0xa5, 0x11, 0x43, 0x78, 0x51,
	0xc6, 0x99, 0xdb, 0xfe, 0xfe, 0x93, 0xeb, 0x61, 0x36, 0xc2, 0x6b, 0xb8, 0x0a, 0x22, 0x68, 0xda,
	0xfe, 0x73, 0xbd, 0xfd, 0x32, 0x0d, 0x2b, 0xa1, 0xb0, 0x29, 0x74, 0xab, 0xcb, 0x54, 0x8c, 0x37,
	0x80, 0x47, 0x1f, 0xb8, 0xff, 0xf3, 0xf4, 0x6e, 0xcb, 0x66, 0x1b, 0x82, 0x71, 0x4c, 0xc8, 0x4b,
	0x68, 0x0c, 0x72, 0x60, 0x2c, 0xc0, 0x98, 0xdb, 0xbf, 0x5c, 0x2f, 0xf4, 0xde, 0xee, 0x50, 0xec,
	0x3f, 0xfa, 0x78, 0xb3, 0xfd, 0xbd, 0x82, 0xc7, 0x27, 0x7a, 0x15, 0x53, 0xf6, 0x80, 0xae, 0xb6,
	0xa1, 0x2d, 0xd0, 0xe2, 0x5c, 0xc9, 0xaa, 0x11, 0x5f, 0xc2, 0xc3, 0x02, 0xfa, 0xac, 0x38, 0xc9,
	0xc4, 0x47, 0x7f, 0xee, 0xe8, 0xde, 0x5c, 0xa1, 0xd8, 0xb9, 0x0e, 0xd2, 0x79, 0xe1, 0x11, 0xb4,
	0x4a, 0xc6, 0x4a, 0x3a, 0x31, 0x9f, 0x94, 0x1d, 0x27, 0xa5, 0xd9, 0x2d, 0xfa, 0x9b, 0xa4, 0x3e,
	0x4c, 0xde, 0xc3, 0x0c, 0xa3, 0x5d, 0x73, 0x99, 0xf8, 0x70, 0xfc, 0x2f, 0xae, 0x39, 0x72, 0x9e,
	0x39, 0xf9, 0x3f, 0x52, 0xd6, 0xc9, 0x90, 0xd0, 0x2f, 0xd0, 0x28, 0x5a, 0x80, 0x3e, 0xd3, 0xb5,
	0xce, 0xfa, 0xc9, 0x64, 0x97, 0x20, 0x99, 0x78, 0x97, 0xd0, 0x6f, 0x70, 0xff, 0x68, 0xbb, 0xb4,
	0x40, 0x3d, 0x6f, 0x25, 0xb3, 0x73, 0x11, 0x93, 0xeb, 0x0f, 0x09, 0x5d, 0x42, 0x4d, 0x5b, 0x2f,
	0x2d, 0xdc, 0xfd, 0xa9, 0x4b, 0xcc, 0x76, 0xe9, 0x79, 0xa6, 0x3a, 0x6d, 0x7c, 0xae, 0xeb, 0xbf,
	0xe3, 0xfa, 0x3a, 0xfe, 0x13, 0xc7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x76, 0x54, 0x77, 0xe3,
	0x34, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Calculator(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error)
	PrimeNumberDecomposition(ctx context.Context, in *PrimeFactorDescomptitionManyTimeRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error)
	LongCalculator(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_LongCalculatorClient, error)
	MaximumEveryOne(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_MaximumEveryOneClient, error)
	SquareRoots(ctx context.Context, in *SquareRootsRequest, opts ...grpc.CallOption) (*SquareRootsResponse, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Calculator(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error) {
	out := new(CalculatorResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Calculator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeFactorDescomptitionManyTimeRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeFactorDescomptitionManyTimeResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberDecompositionClient) Recv() (*PrimeFactorDescomptitionManyTimeResponse, error) {
	m := new(PrimeFactorDescomptitionManyTimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) LongCalculator(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_LongCalculatorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[1], "/calculator.CalculatorService/LongCalculator", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceLongCalculatorClient{stream}
	return x, nil
}

type CalculatorService_LongCalculatorClient interface {
	Send(*LongCalculatorRequest) error
	CloseAndRecv() (*LongCalculatorResponse, error)
	grpc.ClientStream
}

type calculatorServiceLongCalculatorClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceLongCalculatorClient) Send(m *LongCalculatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceLongCalculatorClient) CloseAndRecv() (*LongCalculatorResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongCalculatorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) MaximumEveryOne(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_MaximumEveryOneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[2], "/calculator.CalculatorService/MaximumEveryOne", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceMaximumEveryOneClient{stream}
	return x, nil
}

type CalculatorService_MaximumEveryOneClient interface {
	Send(*MaximumEveryOneRequest) error
	Recv() (*MaximumEveryOneResponse, error)
	grpc.ClientStream
}

type calculatorServiceMaximumEveryOneClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceMaximumEveryOneClient) Send(m *MaximumEveryOneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceMaximumEveryOneClient) Recv() (*MaximumEveryOneResponse, error) {
	m := new(MaximumEveryOneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) SquareRoots(ctx context.Context, in *SquareRootsRequest, opts ...grpc.CallOption) (*SquareRootsResponse, error) {
	out := new(SquareRootsResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/SquareRoots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Calculator(context.Context, *CalculatorRequest) (*CalculatorResponse, error)
	PrimeNumberDecomposition(*PrimeFactorDescomptitionManyTimeRequest, CalculatorService_PrimeNumberDecompositionServer) error
	LongCalculator(CalculatorService_LongCalculatorServer) error
	MaximumEveryOne(CalculatorService_MaximumEveryOneServer) error
	SquareRoots(context.Context, *SquareRootsRequest) (*SquareRootsResponse, error)
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Calculator(ctx context.Context, req *CalculatorRequest) (*CalculatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculator not implemented")
}
func (*UnimplementedCalculatorServiceServer) PrimeNumberDecomposition(req *PrimeFactorDescomptitionManyTimeRequest, srv CalculatorService_PrimeNumberDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecomposition not implemented")
}
func (*UnimplementedCalculatorServiceServer) LongCalculator(srv CalculatorService_LongCalculatorServer) error {
	return status.Errorf(codes.Unimplemented, "method LongCalculator not implemented")
}
func (*UnimplementedCalculatorServiceServer) MaximumEveryOne(srv CalculatorService_MaximumEveryOneServer) error {
	return status.Errorf(codes.Unimplemented, "method MaximumEveryOne not implemented")
}
func (*UnimplementedCalculatorServiceServer) SquareRoots(ctx context.Context, req *SquareRootsRequest) (*SquareRootsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SquareRoots not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Calculator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Calculator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Calculator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Calculator(ctx, req.(*CalculatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeFactorDescomptitionManyTimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumberDecomposition(m, &calculatorServicePrimeNumberDecompositionServer{stream})
}

type CalculatorService_PrimeNumberDecompositionServer interface {
	Send(*PrimeFactorDescomptitionManyTimeResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberDecompositionServer) Send(m *PrimeFactorDescomptitionManyTimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_LongCalculator_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).LongCalculator(&calculatorServiceLongCalculatorServer{stream})
}

type CalculatorService_LongCalculatorServer interface {
	SendAndClose(*LongCalculatorResponse) error
	Recv() (*LongCalculatorRequest, error)
	grpc.ServerStream
}

type calculatorServiceLongCalculatorServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceLongCalculatorServer) SendAndClose(m *LongCalculatorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceLongCalculatorServer) Recv() (*LongCalculatorRequest, error) {
	m := new(LongCalculatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_MaximumEveryOne_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).MaximumEveryOne(&calculatorServiceMaximumEveryOneServer{stream})
}

type CalculatorService_MaximumEveryOneServer interface {
	Send(*MaximumEveryOneResponse) error
	Recv() (*MaximumEveryOneRequest, error)
	grpc.ServerStream
}

type calculatorServiceMaximumEveryOneServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceMaximumEveryOneServer) Send(m *MaximumEveryOneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceMaximumEveryOneServer) Recv() (*MaximumEveryOneRequest, error) {
	m := new(MaximumEveryOneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_SquareRoots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRootsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).SquareRoots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/SquareRoots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).SquareRoots(ctx, req.(*SquareRootsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculator",
			Handler:    _CalculatorService_Calculator_Handler,
		},
		{
			MethodName: "SquareRoots",
			Handler:    _CalculatorService_SquareRoots_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _CalculatorService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LongCalculator",
			Handler:       _CalculatorService_LongCalculator_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "MaximumEveryOne",
			Handler:       _CalculatorService_MaximumEveryOne_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculatorpb/calculator.proto",
}
